apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-svc
  labels:
    app: brain-tasks-app
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
